let languages = [
    "Mandarin",
    "Spanish",
    "English",
    "Hindi",
    "Bengali",
    "Portuguese",
    "Russian",
    "Japanese",
    "Marathi",
    "Telugu",
    "Turkish",
    "Korean",
    "French",
    "German",
    "Vietnamese",
    "Tamil",
    "Javanese",
    "Italian",
    "Egyptian",
    "Gujarati",
    "Iranian",
    "Bhojpuri",
    "Hausa",
    "Kannada",
    "Indonesian",
    "Polish",
    "Yoruba",
    "Malayalam",
    "Odia",
    "Maithili",
    "Burmese",
    "Eastern",
    "Sunda",
    "Sudanese",
    "Algerian",
    "Moroccan",
    "Ukrainian",
    "Igbo",
    "Northern Uzbek",
    "Sindhi",
    "North Levantine Arabic",
    "Romanian",
    "Tagalog",
    "Dutch",
    "Amharic",
    "Magahi",
    "Thai",
    "Saraiki",
    "Khmer",
    "Chhattisgarhi",
    "Somali",
    "Malaysian",
    "Cebuano",
    "Nepali",
    "Mesopotamian Arabic",
    "Assamese",
    "Sinhalese",
    "Northern Kurdish",
    "Hejazi Arabic",
    "Nigerian Fulfulde",
    "Bavarian",
    "South Azerbaijani",
    "Greek",
    "Chittagonian",
    "Kazakh",
    "Deccan",
    "Hungarian",
    "Kinyarwanda",
    "Zulu",
    "South Levantine Arabic",
    "Tunisian Arabic",
    "Sanaani Spoken Arabic",
    "Southern Pashto",
    "Rundi",
    "Czech",
    "Uyghur",
    "Sylheti"
]